require:
  - rubocop-rails
  - rubocop-minitest

AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'bin/*'
    - 'test/dummy/config/**/*'
    - 'test/test_helper.rb'
    - 'test/dummy/db/schema.rb'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassVars:
  Enabled: false

Metrics/MethodLength:
  Max: 40
